apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: production-
  
bases:
  - ../base

replicas:
  - name: production-frontend
    count: 8
    
  - name: production-paymentservice
    count: 8
    
  - name: production-productcatalogservice
    count: 8
