apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-
  
bases:
  - ../base

patches:
  - patch: 
      apiVersion: autoscaling/v2beta2
      kind: HorizontalPodAutoscaler
      metadata:
        name: boutique
      spec:
        minReplicas: 3
    target:
      name: boutique
      kind: HorizontalPodAutoscaler
