apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

bases:
- ../base

images:
- name: boutique/boutique
  newTag: staging

patches:
- path: map.yaml

spec:
  replicas: 3
